####################################################################
# FullyJointTourPreProcessor.py
####################################################################

from Globals import *

instantiationType="DataAssemblyComponent"
#characteristics

# the name of the corresponding class on the C# side:
# this allows for multiple scripts targeting the same component
modelComponentName="PreFJTDataAssembly"  


dataReferences = [

   {"type" : "dbffile",
     "name" : "TodToursDAPFirst",     
     "filename" : cube___DAP_TOUR_TIME_OF_DAY_CHOICE_FIRST_TOURS___, # file paths MUST BE RAW strings (preceded by 'r')
     # parameters could be generally of form source data reference : field
     "columns" : [
                    "personId",
                    "hhId",
                    "persTourId",
                    "homeZoneId",
                    "arrival",
                    "departure"
                    ],
     "deferredLoad" : True
    },

   {"type" : "dbffile",
     "name" : "TodToursDAPSecond",     
     "filename" : cube___DAP_TOUR_TIME_OF_DAY_CHOICE_SECOND_TOURS___, # file paths MUST BE RAW strings (preceded by 'r')
     # parameters could be generally of form source data reference : field
     "columns" : [
                    "personId",
                    "hhId",
                    "persTourId",
                    "homeZoneId",
                    "arrival",
                    "departure"
                    ],
     "deferredLoad" : True
    },

    # These tours are either standalone, where an extra tour is generated for an adult
    # in MakeUpdatedChildTour, looks like the @ columns are set to the adult escort id and tour id




   # In this output are included new escort tours plus 
   #    existing school tours that are now escorted
   #    existing adult mandatory tours that are now also escort tours
   # to find new escort tours we'll just pick tours with tourPurp = TourPurposeEnum.SchoolEscort
   {"type" : "dbffile",
     "name" : "SchoolEscortTours",     
     "filename" : cube___SCHOOL_ESCORT_TOURS___, # file paths MUST BE RAW strings (preceded by 'r')
     "columns" : [
                        "personId",
                        "hhId",
                        "persTourId",
                        "tourPurp",
                        "homeZoneId",
                        "arrival",
                        "departure"
                       # using '@' in data source name indicates this field is generated by the component, so requires some coordination with C# code
                    ],
     "deferredLoad" : True
    },



    {"type" : "dbffile",
     "name" : "DAP",     
     "filename" : cube___DAILY_ACTIVITY_PATTERNS___, # file paths MUST BE RAW strings (preceded by 'r')
     # parameters could be generally of form source data reference : field
     "columns" : [
                "personId",
                "hhId",
                "homeZoneId",
                "DAPId",
                "tourCount"  
                ],
     "deferredLoad" : True
    },



    {"type" : "dbffile",
     "isOutput": "true",
     "name" : "PersonModeledData",     
     "filename" : cube___FULLY_JOINT_TOUR_PRE_PROCESSED_DATA___, # file paths MUST BE RAW strings (preceded by 'r')
     # parameters could be generally of form source data reference : field
     "parameters" : [
                       [ "Persons", "personId"],
                       [ "hhId", "hhId"],
                       [ "homeZone", "homeZoneId"],
                       [ "DAPId", "DAPId"],
                       [ "@tourCount", "tourCount"], # updated from dap count by any generated school escort tours
                       [ "@slotsUsed", "slotsUsed"],
                       [ "@slotsArriv", "slotsArriv"],
                       [ "@slotsDeprt", "slotsDeprt"]
                       # using '@' in data source name indicates this field is generated or updated by the component, so requires some coordination with C# code
                    ]
    },


]


