####################################################################                                                                                                                                                                                           
# TourTimeOfDayIndNonMandEscort.py
# Configuration script for Tour Time Of Day processing of 
# the first tours generated by the DAP model
# these are a mixture of school, university and work tours
####################################################################                                                                                                                                                                                           

#Same configuration is used for non-escort and escort individual non-mandatory tours
# use this to fill in the data reference file name
#inputTourFileName=cube___INDIVIDUAL_NON_MANDATORY_ESCORT_TOUR_DESTINATION_CHOICES___
#inputPersonDaySchedulesFileName=cube___INDIVIDUAL_NON_MANDATORY_TOUR_TIME_OF_DAY_PERSON_SCHEDULES___
#outputTourFileName=cube___INDIVIDUAL_NON_MANDATORY_ESCORT_TOUR_TIME_OF_DAY_CHOICE___
#outputPersonDaySchedulesFileName=cube___INDIVIDUAL_NON_MANDATORY_TOUR_TIME_OF_DAY_PERSON_SCHEDULES___

from TourTimeOfDayIndNonMand import *
dataReferences[0]["filename"] = cube___INDIVIDUAL_NON_MANDATORY_ESCORT_TOUR_DESTINATION_CHOICES___
dataReferences[1]["filename"] = cube___INDIVIDUAL_NON_MANDATORY_TOUR_TIME_OF_DAY_PERSON_SCHEDULES___
dataReferences[3]["filename"] = cube___INDIVIDUAL_NON_MANDATORY_ESCORT_TOUR_TIME_OF_DAY_CHOICE___
dataReferences[4]["filename"] = cube___INDIVIDUAL_NON_MANDATORY_ESCORT_TOUR_TIME_OF_DAY_PERSON_SCHEDULES___

