####################################################################                                                                                                                                                                                           
# TourTimeOfDayWorkBased.py
# Configuration script for Tour Time Of Day processing of 
# work-based tours
# I think this is complete for work-based now
####################################################################                                                                                                                                                                                           

from Globals import * 

instantiationType="MultiModelComponent" 

modelComponentName="TourTimeOfDayWorkBased"

subModels = { 
             "WorkBased": r"TourTimeOfDaySubmodel_WorkBased.py"
            }

dataReferences = [

    {"type" : "dbffile",
     "name" : "Tours",
     "filename" : cube___WORK_BASED_TOUR_DESTINATION_CHOICE___,
     "columns" : [
                    "personId", 
                    "persTourId",   
                    "tourPurp", 
                    "hhId",
                    "homeZoneId",
                    "origZoneId",
                    "hhinc5s",
                    "parentMode",
                    "parTourId",
                    "destZoneId",
                  ],
     "deferredLoad" : True 
    },


    {"type" : "dbffile",
     "name" : "Zones",
     "filename" : cube___ZONES_FILE___, 
     "columns" : ["zoneId", 
                  "term_time", 
                  "park_cost"
                  ]
    },


    # note that for TOD model we are taking the input tours and appending
    # the arrival and departure info, so are NOT ACTUALLY USING THE
    # COLUMN NAMES BELOW;  this is either a little bogus or desirable (or both)
    
   {"type" : "dbffile",
     "isOutput": "true",
     "name" : "OutputTours",     
     "filename" : cube___WORK_BASED_TOUR_TIME_OF_DAY_CHOICE___, # file paths MUST BE RAW strings (preceded by 'r')
     # parameters could be generally of form source data reference : field
     "parameters" : [
                       [ "personId", "personId"],
                       [ "persTourId", "persTourId"],
                       [ "tour", "tourPurp"],
                       [ "hhId", "hhId"],
                       [ "homeZoneId", "homeZoneId"], 
                       [ "origZoneId", "origZoneId"], 
                       [ "hhinc5s", "hhinc5s"], 
                       [ "parentMode", "parentMode"], 
                       [ "parTourId", "parTourId"], 
                       [ "destZoneId", "destZoneId"], 
                       [ "parArrive", "parArrive"], 
                       ["parDepart", "parDepart"], 
                       [ "@arrival", "arrival"],
                       [ "@departure", "departure"],
                       [ "@duration", "duration"],
                       # using '@' in data source name indicates this field is generated by the component, so requires some coordination with C# code
                    ]
    },
    
# # NOTE: FOR Work-based tours the person's used day slots does not change 
# so no schedule output in this file

# TODO: this data is not currently being written -column set would need to be different for each TOD run - maybe I'll update it later
# the responsibility would have to fall to the submodel to write this data
   {"type" : "dbffile",
     "isOutput": "true",
     "name" : "OutputTODStats",     
     "filename" : cube___WORK_BASED_TOUR_TIME_OF_DAY_CHOICE_SUMMARY___, # file paths MUST BE RAW strings (preceded by 'r')
     # parameters could be generally of form source data reference : field
     "parameters" : [
                       [ "arrival", "arrival"],
                       [ "departure", "departure"],
                       [ "countSch", "countSch"],
                       [ "countUni", "countUni"],
                       [ "countWork", "countWork"],
                    ]
    },


]

from MatrixRef4Hwy import matrixReferences
