; Do not change filenames or add or remove FILEI/FILEO statements using an editor. Use Cube/Application Manager.

*copy "%SCENARIO_DIR%\XIT_WKACC_NTL_0_%TPER%.tmp"+"%LOOKUP_DIR%\WalkOverrides.txt" "%SCENARIO_DIR%\XIT_WKACC_NTL_0_%TPER%.ntl"
*copy "%SCENARIO_DIR%\XIT_XFER_NTL_0_%TPER%.tmp"+"%LOOKUP_DIR%\TransferOverrides.txt" "%SCENARIO_DIR%\XIT_XFER_NTL_0_%TPER%.ntl"
*copy "%SCENARIO_DIR%\XIT_DRACC_NTL_0_%TPER%.tmp"+"%LOOKUP_DIR%\DriveOverrides.txt" "%SCENARIO_DIR%\XIT_DRACC_NTL_0_%TPER%.ntl"