---
title: "Make Assignable Database"
output: html_notebook
---


# Overhead
```{r overhead, include = FALSE}
packages_vector <- c("tidyverse",
                     "sf")

need_to_install <- packages_vector[!(packages_vector %in% installed.packages()[,"Package"])]

if (length(need_to_install)) install.packages(need_to_install)

for (package in packages_vector) {
  library(package, character.only = TRUE)
}

```

# Remote I/O
```{r remote-io}
model_in_dir <- "../../models/network_standard_batch/"
model_out_dir <- "../../data/test_new_network_outputs/" 

am_file_name <- paste0(model_out_dir, "HWY_LDNET_1_AM.shp")

output_file_name <- paste0(model_in_dir, "lookup_files/assignable.csv")
```

# Parameters
```{r parameters}

```


# Data Reads
```{r read}
am_sf <- st_read(am_file_name)
```

# Reductions 
```{r reductions}
output_df <- tibble(A = am_sf$A,
                    B = am_sf$B,
                    drive_access = am_sf$DRIVE_ACCES,
                    centroid = am_sf$CENTROIDCON,
                    assign_group = am_sf$ASSIGN_GROU,
                    segment_id = am_sf$SEGMENT_ID,
                    lanes = am_sf$LANES,
                    RCI = am_sf$RCI,
                    volume = am_sf$V_1) %>%
  mutate(assignable = 0L) %>%
  mutate(assignable = if_else(centroid == 1, 1L, assignable)) %>%
  mutate(assignable = if_else(lanes > 1, 1L, assignable)) %>%
  mutate(assignable = if_else(volume > 0, 1L, assignable)) %>%
  select(A, B, ASSIGN = assignable)

  
```

# Write
```{r write}
write_csv(output_df, output_file_name)
```


