---
title: "Make Transit Boardings Viewer"
output: html_notebook
---

# Overhead
```{r overhead, include = FALSE}
packages_vector <- c("foreign",
                     "tidyverse",
                     "sf",
                     "lubridate")

need_to_install <- packages_vector[!(packages_vector %in% installed.packages()[,"Package"])]

if (length(need_to_install)) install.packages(need_to_install)

for (package in packages_vector) {
  library(package, character.only = TRUE)
}

```

# Remote I/O
```{r remote-io}
model_out_dir <- "../../data/test_new_network_outputs/"
interim_dir <- "../../data/interim/"

loaded_file_prefix <- paste0(model_out_dir, "XIT_")

output_file_name <- paste0(interim_dir, "simulated-transit-boardings-for-tableau.csv")
```

# Data Reads
```{r read}
routes_df <- read_csv(paste0(transit_dir, "routes.txt"), col_types = "ciccciccc")
freq_df <- read_csv(paste0(transit_dir, "frequencies.txt"), col_types = "citt")
trips_df <- read_csv(paste0(transit_dir, "trips.txt"), col_types = cols(.default = col_character(),
                                                                        direction_id = col_integer(),
                                                                        block_id = col_integer(),
                                                                        shape_id = col_integer()))
stops_df <- read_csv(paste0(transit_dir, "stops.txt"), col_types  = cols(.default = col_character(),
                                                                         stop_lat = col_double(),
                                                                         stop_lon = col_double(),
                                                                         model_node_id = col_integer()))
shapes_df <- read_csv(paste0(transit_dir, "shapes.txt"), col_types = "iddicc")
stop_times_df <- read_csv(paste0(transit_dir, "stop_times.txt"), col_types = cols(.default = col_integer(),
                                                                                  stop_id = col_character(),
                                                                                  trip_id = col_character(),
                                                                                  arrival_time = col_time(),
                                                                                  departure_time = col_time(),
                                                                                  stop_distance = col_double(),
                                                                                  timepoint = col_character(),
                                                                                  stop_is_skipped = col_character()))

nodes_sf <- st_read(paste0(road_dir, "node.geojson"), stringsAsFactors = FALSE)

loaded_df <- tibble()
for (period in c("PK", "OP")) {
  for (access in c("WK", "DR")){
    
    filename <- paste0(loaded_file_prefix, access, "_LD_4_", period, ".DBF")
    df <- read.dbf(filename, as.is = TRUE)
    df <- mutate(df, path = paste0(period, "---", access))
    loaded_df <- bind_rows(loaded_df, df)
    
  }
}
```

# Reductions
```{r reductions}
boardings_df <- loaded_df %>%
  mutate(transit = str_detect(NAME, "\\*", negate = TRUE)) %>%
  filter(transit) %>%
  group_by(NAME, A, path) %>%
  summarise(boardings = sum(ONA), .groups = "drop") %>%
  mutate(walk_path = str_detect(path, "WK")) %>%
  mutate(walk_boardings = if_else(walk_path, boardings, 0.0)) %>%
  mutate(drive_boardings = if_else(!walk_path, boardings, 0.0)) %>%
  mutate(boardings = walk_boardings + drive_boardings) %>%
  select(model_name = NAME, model_node_id = A, walk_boardings, drive_boardings, boardings) %>%
  group_by(model_name, model_node_id) %>%
  summarise(boardings = sum(boardings), 
            walk_boardings = sum(walk_boardings), 
            drive_boardings = sum(drive_boardings), 
            .groups = "drop")

nodes_df <- bind_cols(tibble(model_node_id = nodes_sf$model_node_id), as_tibble(st_coordinates(nodes_sf))) %>%
  rename(lng = X, lat = Y)
  
output_df <- select(routes_df, route_id, agency_id, route_short_name, route_long_name) %>%
  left_join(select(trips_df, route_id, service_id, trip_id, trip_headsign, direction_id, shape_id),
            ., by = c("route_id")) %>%
  left_join(., freq_df, by = c("trip_id")) %>%
  left_join(select(stop_times_df, trip_id, stop_id, stop_sequence), ., by = c("trip_id")) %>%
  left_join(., select(stops_df, stop_id, model_node_id, stop_name, stop_lat, stop_lon), by = c("stop_id")) %>%
  mutate(tod_name = if_else(start_time == hms("06:00:00"), "pk", "op")) %>%
  mutate(model_name = paste0(agency_id, "_", route_id, "_", tod_name, "_d", direction_id, "_s", shape_id)) %>%
  left_join(., boardings_df, by = c("model_name", "model_node_id")) %>%
  mutate(boardings = replace_na(boardings, 0.0))

sum(output_df$boardings)
```

# Write
```{r write}
write_csv(output_df, file = output_file_name)
```


