# Set Inputs and Interimediate File Names - Part 2
cube___OD_DISTANCE_MATRIX___ = r"C:\projects\met_council_git\data\interim\HWY_SKIM_4_AM.skm"
cube___AM_PEAK_MATRIX___ = r"C:\projects\met_council_git\data\interim\HWY_SKIM_4_AM.skm"
cube___MIDDAY_MATRIX___ = r"C:\projects\met_council_git\data\interim\HWY_SKIM_4_MD.skm"
cube___PM_PEAK_MATRIX___ = r"C:\projects\met_council_git\data\interim\HWY_SKIM_4_PM.skm"
cube___OVERNIGHT_MATRIX___ = r"C:\projects\met_council_git\data\interim\HWY_SKIM_4_NT.skm"
cube___NM_MATRIX___ = r"C:\projects\met_council_git\data\interim\NM_SKIM.skm"
cube___PEAK_WALK_TO_TRANSIT_MATRIX___ = r"C:\projects\met_council_git\data\interim\XIT_WK_SKIM_4_PK.skm"
cube___PEAK_DRIVE_TO_TRANSIT_MATRIX___ = r"C:\projects\met_council_git\data\interim\XIT_DR_SKIM_4_PK.skm"
cube___OFF_PEAK_WALK_TO_TRANSIT_MATRIX___ = r"C:\projects\met_council_git\data\interim\XIT_WK_SKIM_4_OP.skm"
cube___OFF_PEAK_DRIVE_TO_TRANSIT_MATRIX___ = r"C:\projects\met_council_git\data\interim\XIT_DR_SKIM_4_OP.skm"
AM1___TRIP_TABLE_MATRIX___ = r"C:\projects\met_council_git\data\interim\HWY_TRIP_5_AM1.trp"
AM2___TRIP_TABLE_MATRIX___ = r"C:\projects\met_council_git\data\interim\HWY_TRIP_5_AM2.trp"
AM3___TRIP_TABLE_MATRIX___ = r"C:\projects\met_council_git\data\interim\HWY_TRIP_5_AM3.trp"
AM4___TRIP_TABLE_MATRIX___ = r"C:\projects\met_council_git\data\interim\HWY_TRIP_5_AM4.trp"
MD___TRIP_TABLE_MATRIX___ = r"C:\projects\met_council_git\data\interim\HWY_TRIP_5_MD.trp"
PM1___TRIP_TABLE_MATRIX___ = r"C:\projects\met_council_git\data\interim\HWY_TRIP_5_PM1.trp"
PM2___TRIP_TABLE_MATRIX___ = r"C:\projects\met_council_git\data\interim\HWY_TRIP_5_PM2.trp"
PM3___TRIP_TABLE_MATRIX___ = r"C:\projects\met_council_git\data\interim\HWY_TRIP_5_PM3.trp"
PM4___TRIP_TABLE_MATRIX___ = r"C:\projects\met_council_git\data\interim\HWY_TRIP_5_PM4.trp"
EV___TRIP_TABLE_MATRIX___ = r"C:\projects\met_council_git\data\interim\HWY_TRIP_5_EV.trp"
NT___TRIP_TABLE_MATRIX___ = r"C:\projects\met_council_git\data\interim\HWY_TRIP_5_ON.trp"
PeakTransit___TRIP_TABLE_MATRIX___ = r"C:\projects\met_council_git\data\interim\XIT_TRIP_5_PK.trp"
OffPeakTransit___TRIP_TABLE_MATRIX___ = r"C:\projects\met_council_git\data\interim\XIT_TRIP_5_OP.trp"
#End of Configuration File