# This file passes file names to the Python TourCast configuration
import sys
import os
import re

directory_path = os.path.dirname(sys.argv[0])
directory_path = os.path.abspath(directory_path)
replacement_index = directory_path.rfind("\\")
directory_path = directory_path[:replacement_index + 1]

tourcast_dir = sys.argv[1]
scenario_dir = sys.argv[2]
iter = sys.argv[3]
prev_iter = str(int(iter) - 1)
households = sys.argv[4]
persons = sys.argv[5]

f = open(tourcast_dir + "/script/CubeKeyValues.py", "w")
f.write("# Set Inputs and Intermediate File Names - Part 1\n")
f.write("cube___HOUSEHOLDS_FILE___ = r\"" + directory_path + households + "\"\n")
f.write("cube___WORK_BASED_TOUR_TIME_OF_DAY_CHOICE___ = r\"" + directory_path + scenario_dir + "\\TC_OutputTODToursWorkBased_" + iter + ".dbf" + "\"\n")
f.write("cube___ZONES_FILE___ = r\"" + directory_path + scenario_dir + "\\zones_" + iter + ".dbf" + "\"\n")
f.write("cube___PERSONS_FILE___ = r\"" + directory_path +  persons + "\"\n")
f.write("cube___DAILY_ACTIVITY_PATTERNS___ = r\"" + directory_path + scenario_dir + "\\TC_OutputDAP_" + iter + ".dbf" + "\"\n")
f.write("cube___MODELED_HOUSEHOLDS_FILE___ = r\"" + directory_path + scenario_dir + "\\TC_HouseholdModeledData_" + iter + ".dbf" + "\"\n")
f.write("cube___PASS_MODEL___ = r\"" + directory_path + scenario_dir + "\\TC_PassModel_" + iter + ".dbf" + "\"\n")
f.write("cube___PASS_MODEL_SUMMARY___ = r\"" + directory_path + scenario_dir + "\\TC_PassModelSummary_" + iter + ".dbf" + "\"\n")
f.write("cube___DAILY_ACTIVITY_PATTERNS_FIRST_TOURS___ = r\"" + directory_path + scenario_dir + "\\TC_OutputDAPFirstTours_" + iter + ".dbf" + "\"\n")
f.write("cube___DAILY_ACTIVITY_PATTERNS_SECOND_TOURS___ = r\"" + directory_path + scenario_dir + "\\TC_OutputDAPSecondTours_" + iter + ".dbf" + "\"\n")
f.write("cube___DAILY_ACTIVITY_PATTERNS_SUMMARY___ = r\"" + directory_path + scenario_dir + "\\TC_OutputDAPStats_" + iter + ".dbf" + "\"\n")
f.write("cube___DAILY_ACTIVITY_PATTERN_PRE_PROCESSED_DATA___ = r\"" + directory_path + scenario_dir + "\\TC_OutputPersonsPreDAP_" + iter + ".dbf" + "\"\n")
f.write("cube___FULLY_JOINT_TOURS___ = r\"" + directory_path + scenario_dir + "\\TC_FullyJointTours_" + iter + ".dbf" + "\"\n")
f.write("cube___FULLY_JOINT_TOUR_PERSON_LINK_TABLE___ = r\"" + directory_path + scenario_dir + "\\TC_FullyJointPersonTourLinkTable_" + iter + ".dbf" + "\"\n")
f.write("cube___FULLY_JOINT_TOUR_SUMMARY___ = r\"" + directory_path + scenario_dir + "\\TC_FullyJointTourSummaryByHousehold_" + iter + ".dbf" + "\"\n")
f.write("cube___FULLY_JOINT_TOUR_PARTICIPATION_SUMMARY___ = r\"" + directory_path + scenario_dir + "\\TC_FullyJointTourParticipationSummary_" + iter + ".dbf" + "\"\n")
f.write("cube___FULLY_JOINT_TOUR_GENERATION_SUMMARY___ = r\"" + directory_path + scenario_dir + "\\TC_FullyJointTourGenerationSummary_" + iter + ".dbf" + "\"\n")
f.write("cube___FULLY_JOINT_TOUR_DESTINATION_CHOICE___ = r\"" + directory_path + scenario_dir + "\\TC_OutputTourDestinationChoiceFullyJoint_" + iter + ".dbf" + "\"\n")
f.write("cube___FULLY_JOINT_TOUR_DESTINATION_CHOICE_SUMMARY___ = r\"" + directory_path + scenario_dir + "\\TC_OutputTourDestinationChoiceFullyJointStats_" + iter + ".txt" + "\"\n")
f.write("cube___FULLY_JOINT_TOUR_PRE_PROCESSED_DATA___ = r\"" + directory_path + scenario_dir + "\\TC_PreFJTPersonModeledData_" + iter + ".dbf" + "\"\n")
f.write("cube___FULLY_JOINT_TOUR_TIME_OF_DAY___ = r\"" + directory_path + scenario_dir + "\\TC_OutputTODToursFullyJoint_" + iter + ".dbf" + "\"\n")
f.write("cube___FULLY_JOINT_TOUR_PERSON_SCHEDULES___ = r\"" + directory_path + scenario_dir + "\\TC_OutputPersonTODSchedulesFullyJoint_" + iter + ".dbf" + "\"\n")
f.write("cube___INDIVIDUAL_NON_MANDATORY_TOURS___ = r\"" + directory_path + scenario_dir + "\\TC_OutputINMTours_" + iter + ".dbf" + "\"\n")
f.write("cube___INDIVIDUAL_NON_MANDATORY_ESCORT_TOUR_DESTINATION_CHOICES___ = r\"" + directory_path + scenario_dir + "\\TC_OutputTourDestinationChoiceINMEscort_" + iter + ".dbf" + "\"\n")
f.write("cube___INDIVIDUAL_NON_MANDATORY_ESCORT_TOUR_DESTINATION_CHOICE_SUMMARY___ = r\"" + directory_path + scenario_dir + "\\TC_OutputTourDestinationChoiceINMEscortStats_" + iter + ".txt" + "\"\n")
f.write("cube___INDIVIDUAL_NON_MANDATORY_TOUR_PRE_PROCESSED_DATA___ = r\"" + directory_path + scenario_dir + "\\TC_PreINMPersonModeledData_" + iter + ".dbf" + "\"\n")
f.write("cube___INDIVIDUAL_NON_MANDATORY_TOUR_DESTINATION_CHOICES___ = r\"" + directory_path + scenario_dir + "\\TC_OutputTourDestinationChoiceINM_" + iter + ".dbf" + "\"\n")
f.write("cube___INDIVIDUAL_NON_MANDATORY_TOUR_DESTINATION_CHOICE_SUMMARY___ = r\"" + directory_path + scenario_dir + "\\TC_OutputTourDestinationChoiceINMStats_" + iter + ".txt" + "\"\n")
f.write("cube___FIRST_MANDATORY_TOUR_TIME_OF_DAY___ = r\"" + directory_path + scenario_dir + "\\TC_OutputPreTODFirstTours_" + iter + ".dbf" + "\"\n")
f.write("cube___SECOND_MANDATORY_TOUR_TIME_OF_DAY___ = r\"" + directory_path + scenario_dir + "\\TC_OutputPreTODSecondTours_" + iter + ".dbf" + "\"\n")
f.write("cube___SCHOOL_ESCORT_TOURS___ = r\"" + directory_path + scenario_dir + "\\TC_OutputPostSchoolEscortTours_" + iter + ".dbf" + "\"\n")
f.write("cube___SCHOOL_ESCORT_STOPS___ = r\"" + directory_path + scenario_dir + "\\TC_OutputSchoolEscortStops_" + iter + ".dbf" + "\"\n")
f.write("cube___SCHOOL_ESCORT_SUMMARY___ = r\"" + directory_path + scenario_dir + "\\TC_OutputSchoolEscortStats_" + iter + ".dbf" + "\"\n")
f.write("cube___SCHOOL_LOCATIONS___ = r\"" + directory_path + scenario_dir + "\\TC_OutputSchoolLocationTest_" + iter + ".dbf" + "\"\n")
f.write("cube___STOP_DESTINATION_CHOICE___ = r\"" + directory_path + scenario_dir + "\\TC_OutputStopsWithDestinations_" + iter + ".dbf" + "\"\n")
f.write("cube___STOP_DESTINATION_CHOICE_SUMMARY___ = r\"" + directory_path + scenario_dir + "\\TC_OutputStopDestinationChoiceStats_" + iter + ".txt" + "\"\n")
f.write("cube___STOP_GENERATION_STOPS_HOME_BASED___ = r\"" + directory_path + scenario_dir + "\\TC_OutputStops_" + iter + ".dbf" + "\"\n")
f.write("cube___STOP_GENERATION_TOURS_HOME_BASED___ = r\"" + directory_path + scenario_dir + "\\TC_OutputToursAfterStopGen_" + iter + ".dbf" + "\"\n")
f.write("cube___TRIP_TIME_OF_DAY___ = r\"" + directory_path + scenario_dir + "\\TC_OutputTrips_" + iter + ".dbf" + "\"\n")
f.write("cube___STOPS_WITH_TOUR_OFFSET_TIMES___ = r\"" + directory_path + scenario_dir + "\\TC_OutputStopsWithTourOffsetTimes_" + iter + ".dbf" + "\"\n")
f.write("cube___SCHOOL_LOCATIONS_SUMMARY___ = r\"" + directory_path + scenario_dir + "\\TC_OutputSchoolLocationStatsTest_" + iter + ".txt" + "\"\n")
f.write("cube___UNIVERSITY_TOUR_DESTINATION_CHOICE_FIRST_TOURS___ = r\"" + directory_path + scenario_dir + "\\TC_OutputTourDestinationChoiceUniversityFirstToursTest_" + iter + ".dbf" + "\"\n")
f.write("cube___UNIVERSITY_TOUR_DESTINATION_CHOICE_SECOND_TOURS___ = r\"" + directory_path + scenario_dir + "\\TC_OutputTourDestinationChoiceUniversitySecondToursTest_" + iter + ".dbf" + "\"\n")
f.write("cube___UNIVERSITY_TOUR_DESTINATION_CHOICE_SUMMARY___ = r\"" + directory_path + scenario_dir + "\\TC_OutputTourDestinationChoiceUniversityStats_" + iter + ".txt" + "\"\n")
f.write("cube___WORK_TOUR_DESTINATION_CHOICE_FIRST_TOURS___ = r\"" + directory_path + scenario_dir + "\\TC_OutputTourDestinationChoiceWorkFirstToursTest_" + iter + ".dbf" + "\"\n")
f.write("cube___WORK_TOUR_DESTINATION_CHOICE_SECOND_TOURS___ = r\"" + directory_path + scenario_dir + "\\TC_OutputTourDestinationChoiceWorkSecondToursTest_" + iter + ".dbf" + "\"\n")
f.write("cube___WORK_TOUR_DESTINATION_CHOICE_SUMMARY___ = r\"" + directory_path + scenario_dir + "\\TC_OutputTourDestinationChoiceWorkStats_" + iter + ".txt" + "\"\n")
f.write("cube___HOME_BASED_TOUR_MODE_CHOICE___ = r\"" + directory_path + scenario_dir + "\\TC_OutputModeChoice_" + iter + ".dbf" + "\"\n")
f.write("cube___HOME_BASED_TOUR_MODE_CHOICE_SUMMARY___ = r\"" + directory_path + scenario_dir + "\\TC_OutputModeChoiceForStats_" + iter + ".dbf" + "\"\n")
f.write("cube___DAP_TOUR_TIME_OF_DAY_CHOICE_FIRST_TOURS___ = r\"" + directory_path + scenario_dir + "\\TC_OutputTODToursDAPFirst_" + iter + ".dbf" + "\"\n")
f.write("cube___DAP_TOUR_TIME_OF_DAY_PERSON_SCHEDULES_FIRST_TOURS___ = r\"" + directory_path + scenario_dir + "\\TC_OutputPersonTODSchedulesDAPFirstTours_" + iter + ".dbf" + "\"\n")
f.write("cube___DAP_TOUR_TIME_OF_DAY_FIRST_TOUR_CHOICE_SUMMARY___ = r\"" + directory_path + scenario_dir + "\\TC_OutputTODStatsDAPFirstTours_" + iter + ".dbf" + "\"\n")
f.write("cube___DAP_TOUR_TIME_OF_DAY_CHOICE_SECOND_TOURS___ = r\"" + directory_path + scenario_dir + "\\TC_OutputTODToursDAPSecond_" + iter + ".dbf" + "\"\n")
f.write("cube___DAP_TOUR_TIME_OF_DAY_PERSON_SCHEDULES_SECOND_TOURS___ = r\"" + directory_path + scenario_dir + "\\TC_OutputPersonTODSchedulesDAPSecondTours_" + iter + ".dbf" + "\"\n")
f.write("cube___DAP_TOUR_TIME_OF_DAY_SECOND_TOUR_CHOICE_SUMMARY___ = r\"" + directory_path + scenario_dir + "\\TC_OutputTODStatsDAPSecondTours_" + iter + ".dbf" + "\"\n")
f.write("cube___INDIVIDUAL_NON_MANDATORY_ESCORT_TOUR_TIME_OF_DAY_CHOICE___ = r\"" + directory_path + scenario_dir + "\\TC_OutputTODToursIndNonMandEscort_" + iter + ".dbf" + "\"\n")
f.write("cube___INDIVIDUAL_NON_MANDATORY_ESCORT_TOUR_TIME_OF_DAY_PERSON_SCHEDULES___ = r\"" + directory_path + scenario_dir + "\\TC_OutputPersonTODSchedulesIndNonMand_" + iter + ".dbf" + "\"\n")
f.write("cube___INDIVIDUAL_NON_MANDATORY_TOUR_TIME_OF_DAY_CHOICE___ = r\"" + directory_path + scenario_dir + "\\TC_OutputTODToursIndNonMand_" + iter + ".dbf" + "\"\n")
f.write("cube___INDIVIDUAL_NON_MANDATORY_TOUR_TIME_OF_DAY_PERSON_SCHEDULES___ = r\"" + directory_path + scenario_dir + "\\TC_OutputPersonTODSchedulesIndNonMandNonEscort_" + iter + ".dbf" + "\"\n")
f.write("cube___INDIVIDUAL_NON_MANDATORY_TOUR_TIME_OF_DAY_SUMMARY___ = r\"" + directory_path + scenario_dir + "\\TC_INDIVIDUAL_NON_MANDATORY_TOUR_TIME_OF_DAY_SUMMARY_" + iter + ".dbf" + "\"\n")
f.write("cube___TRIPS_WITH_MODES___ = r\"" + directory_path + scenario_dir + "\\TC_OutputTripModes_" + iter + ".dbf" + "\"\n")
f.write("cube___WORKPLACE_LOCATIONS___ = r\"" + directory_path + scenario_dir + "\\TC_OutputPersonsWorkplaceLocationTest_" + iter + ".dbf" + "\"\n")
f.write("cube___WORKPLACE_LOCATIONS_SUMMARY___ = r\"" + directory_path + scenario_dir + "\\TC_OutputPersonsWorkplaceLocationStats_" + iter + ".txt" + "\"\n")
f.write("cube___NUM_CARS_PER_HOUSEHOLD___ = r\"" + directory_path + scenario_dir + "\\TC_OutputNCars_" + iter + ".dbf" + "\"\n")
f.write("cube___VEHICLE_AVAILABILITY_SUMMARY___ = r\"" + directory_path + scenario_dir + "\\TC_OutputAAStats_" + iter + ".dbf" + "\"\n")
f.write("cube___PERSONS_ADULTS___ = r\"" + directory_path + scenario_dir + "\\TC_OutputPersonsAdultsAA_" + iter + ".dbf" + "\"\n")
f.write("cube___PERSONS_CHILDREN___ = r\"" + directory_path + scenario_dir + "\\TC_OutputPersonsChildrenAA_" + iter + ".dbf" + "\"\n")
f.write("cube___WORK_BASED_SUBTOURS___ = r\"" + directory_path + scenario_dir + "\\TC_OutputWBSTGeneration_" + iter + ".dbf" + "\"\n")
f.write("cube___WORK_BASED_STOPS___ = r\"" + directory_path + scenario_dir + "\\TC_OutputStopsWorkBasedStopGen_" + iter + ".dbf" + "\"\n")
f.write("cube___WORK_BASED_TOUR_DESTINATION_CHOICE___ = r\"" + directory_path + scenario_dir + "\\TC_OutputTourDestinationChoiceWorkBased_" + iter + ".dbf" + "\"\n")
f.write("cube___WORK_BASED_TOUR_DESTINATION_CHOICE_SUMMARY___ = r\"" + directory_path + scenario_dir + "\\TC_OutputTourDestinationChoiceWorkBasedStats_" + iter + ".txt" + "\"\n")
f.write("cube___WORK_BASED_TOUR_TIME_OF_DAY_CHOICE_SUMMARY___ = r\"" + directory_path + scenario_dir + "\\TC_OutputTODStatsWorkBased_" + iter + ".dbf" + "\"\n")
f.write("cube___WORKPLACE_LOCATIONS_PERSONS___ = r\"" + directory_path + scenario_dir + "\\TC_OutputUsualWorkplaceExistenceTest_" + iter + ".dbf" + "\"\n")
f.write("cube___WORKPLACE_LOCATIONS_PERSONS_SUMMARY___ = r\"" + directory_path + scenario_dir + "\\TC_OutputPersonStats_UsualWorkplaceExistence_" + iter + ".dbf" + "\"\n")
f.write("cube___WORK_BASED_TOUR_PRE_PROCESSED_DATA___ = r\"" + directory_path + scenario_dir + "\\TC_OutputPreWBST_" + iter + ".dbf" + "\"\n")
f.write("cube___WORK_BASED_TOUR_MODE_CHOICE___ = r\"" + directory_path + scenario_dir + "\\TC_OutputModeChoiceWorkBased_" + iter + ".dbf" + "\"\n")
f.write("cube___WORK_BASED_TOUR_MODE_CHOICE_SUMMARY___ = r\"" + directory_path + scenario_dir + "\\TC_OutputModeChoiceForStatsWorkBased_" + iter + ".dbf" + "\"\n")
f.write("cube___TRIP_TABLE_MATRIX___ = r\"" + directory_path + scenario_dir + "\\TripTable.mat" + "\"\n")
f.write("#End of Configuration File")
f.close()

f = open(tourcast_dir + "/script/MatrixKeyValues.py", "w")
f.write("# Set Inputs and Intermediate File Names - Part 2\n")
f.write("cube___OD_DISTANCE_MATRIX___ = r\"" + directory_path + scenario_dir +"\\HWY_SKIM_" + prev_iter + "_AM.skm\"\n")
f.write("cube___AM_PEAK_MATRIX___ = r\"" + directory_path + scenario_dir +"\\HWY_SKIM_" + prev_iter + "_AM.skm\"\n")
f.write("cube___MIDDAY_MATRIX___ = r\"" + directory_path + scenario_dir +"\\HWY_SKIM_" + prev_iter + "_MD.skm\"\n")
f.write("cube___PM_PEAK_MATRIX___ = r\"" + directory_path + scenario_dir +"\\HWY_SKIM_" + prev_iter + "_PM.skm\"\n")
f.write("cube___OVERNIGHT_MATRIX___ = r\"" + directory_path + scenario_dir +"\\HWY_SKIM_" + prev_iter + "_NT.skm\"\n")
f.write("cube___NM_MATRIX___ = r\"" + directory_path + scenario_dir +"\\NM_SKIM.skm\"\n")
f.write("cube___PEAK_WALK_TO_TRANSIT_MATRIX___ = r\"" + directory_path + scenario_dir +"\\XIT_WK_SKIM_" + prev_iter + "_PK.skm\"\n")
f.write("cube___PEAK_DRIVE_TO_TRANSIT_MATRIX___ = r\"" + directory_path + scenario_dir +"\\XIT_DR_SKIM_" + prev_iter + "_PK.skm\"\n")
f.write("cube___OFF_PEAK_WALK_TO_TRANSIT_MATRIX___ = r\"" + directory_path + scenario_dir +"\\XIT_WK_SKIM_" + prev_iter + "_OP.skm\"\n")
f.write("cube___OFF_PEAK_DRIVE_TO_TRANSIT_MATRIX___ = r\"" + directory_path + scenario_dir +"\\XIT_DR_SKIM_" + prev_iter + "_OP.skm\"\n")
f.write("AM1___TRIP_TABLE_MATRIX___ = r\"" + directory_path + scenario_dir +"\\HWY_TRIP_" + iter + "_AM1.trp\"\n")
f.write("AM2___TRIP_TABLE_MATRIX___ = r\"" + directory_path + scenario_dir +"\\HWY_TRIP_" + iter + "_AM2.trp\"\n")
f.write("AM3___TRIP_TABLE_MATRIX___ = r\"" + directory_path + scenario_dir +"\\HWY_TRIP_" + iter + "_AM3.trp\"\n")
f.write("AM4___TRIP_TABLE_MATRIX___ = r\"" + directory_path + scenario_dir +"\\HWY_TRIP_" + iter + "_AM4.trp\"\n")
f.write("MD___TRIP_TABLE_MATRIX___ = r\"" + directory_path + scenario_dir +"\\HWY_TRIP_" + iter + "_MD.trp\"\n")
f.write("PM1___TRIP_TABLE_MATRIX___ = r\"" + directory_path + scenario_dir +"\\HWY_TRIP_" + iter + "_PM1.trp\"\n")
f.write("PM2___TRIP_TABLE_MATRIX___ = r\"" + directory_path + scenario_dir +"\\HWY_TRIP_" + iter + "_PM2.trp\"\n")
f.write("PM3___TRIP_TABLE_MATRIX___ = r\"" + directory_path + scenario_dir +"\\HWY_TRIP_" + iter + "_PM3.trp\"\n")
f.write("PM4___TRIP_TABLE_MATRIX___ = r\"" + directory_path + scenario_dir +"\\HWY_TRIP_" + iter + "_PM4.trp\"\n")
f.write("EV___TRIP_TABLE_MATRIX___ = r\"" + directory_path + scenario_dir +"\\HWY_TRIP_" + iter + "_EV.trp\"\n")
f.write("NT___TRIP_TABLE_MATRIX___ = r\"" + directory_path + scenario_dir +"\\HWY_TRIP_" + iter + "_ON.trp\"\n")
f.write("PeakTransit___TRIP_TABLE_MATRIX___ = r\"" + directory_path + scenario_dir +"\\XIT_TRIP_" + iter + "_PK.trp\"\n")
f.write("OffPeakTransit___TRIP_TABLE_MATRIX___ = r\"" + directory_path + scenario_dir +"\\XIT_TRIP_" + iter + "_OP.trp\"\n")
f.write("#End of Configuration File")
f.close()
